#! /bin/sh

## Environtment
DIR="${HOME}/.config/bspwm"
export PATH="${PATH}:${DIR}/bin"

## Window rules
source "${DIR}/rules"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh --shades
alacritty
