# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=$HOME/.asdf/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:/opt/homebrew/bin
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export TERM="xterm-256color"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Custom completion directory
ZSH_COMP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/completions"
[[ -d "$ZSH_COMP_DIR" ]] || mkdir -p "$ZSH_COMP_DIR"
fpath=("$ZSH_COMP_DIR" $fpath)

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# Created by newuser for 5.8

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

export POWERLEVEL9K_INSTANT_PROMPT=quiet
zinit ice depth=1; zinit light romkatv/powerlevel10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      zdharma-continuum/fast-syntax-highlighting \
    OMZP::colored-man-pages \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions \

# omz plugin
zinit light-mode for \
  as"completion" \
    OMZP::docker/completions/_docker \
    OMZL::completion.zsh

zinit light-mode for \
    hlissner/zsh-autopair \
    superbrothers/zsh-kubectl-prompt \
    OMZP::kubectl \
    OMZP::gitignore \
    OMZP::cp \
    OMZP::asdf \
    OMZL::clipboard.zsh \
    OMZL::history.zsh

zinit ice atload"unalias grv"; zinit snippet OMZP::git

zinit from"gh-r" as"program" mv"direnv* -> direnv" \
    atclone'./direnv hook zsh > zhook.zsh' atpull'%atclone' \
    pick"direnv" src="zhook.zsh" for \
        direnv/direnv

# zsh-vi-mode
zinit ice depth=1; zinit light jeffreytse/zsh-vi-mode
# For postponing loading `fzf`
zinit ice lucid wait; zinit snippet OMZP::fzf

zinit ice depth=1; zinit light Tarrasch/zsh-autoenv


load_completion_with_zinit() {
  # Check if an argument is provided
  if [ -z "$1" ]; then
    echo "Usage: load_completion_with_zinit <command>"
    return 1
  fi

  # Generate and load completion script using Zinit
  zinit ice as"completion" wait"0" lucid
  zinit snippet <<<"$($1 completion zsh)"
}

_exists() { (( $+commands[$1])) }
_exists lsd     && alias ls='lsd' && alias ll='ls -lh'
_exists eza     && alias ls='eza --icons' && alias ll='ls -lh'
_exists htop    && alias top='htop'
_exists fdfind  && alias fd='fdfind'
_exists batcat  && alias cat='batcat'
_exists free    && alias free='free -h'
_exists less    && export PAGER=less
_exists less    && alias more='less'
_exists ag      && alias grep='ag'
_exists rg      && alias grep='rg'
_exists curlie  && alias curl='curlie' && compdef _curl curlie
_exists delta   && alias diff='delta'
_exists difft   && alias diff='difft' && export KUBECTL_EXTERNAL_DIFF="difft"
# _exists kubectl && load_completion_with_zinit kubectl

if _exists nvim; then
    export EDITOR=nvim
    export VISUAL=nvim
    export MANPAGER="nvim +Man!"
    alias vim='nvim'
    alias vi='nvim'
fi

unfunction _exists

# Copies stdin to clipboard using OSC 52 escape sequence
if [[ "$OSTYPE" != "darwin"* && ("$TERM" == "xterm"* || "$TERM" == "screen"* || "$TERM" == "tmux"*) ]]; then
    # OSC 52 support for non-macOS terminals
    function clipcopy() {
      local content_tocopy
      content_tocopy=$(cat "${1:-/dev/stdin}" | base64 | tr -d '\n')
      printf "\033]52;c;%s\a" "$content_tocopy" > /dev/tty
    }
fi

# Auto-generate completions for installed tools
_ensure_completion() {
  local cmd="$1" generator="$2"
  local comp_file="$ZSH_COMP_DIR/_$cmd"
  (( $+commands[$cmd] )) && [[ ! -f "$comp_file" ]] && eval "$generator > $comp_file" 2>/dev/null
}

_ensure_completion kubectl  "kubectl completion zsh"
_ensure_completion helm     "helm completion zsh"
_ensure_completion gh       "gh completion -s zsh"
_ensure_completion uv       "uv generate-shell-completion zsh"

unfunction _ensure_completion
